# Generated by Django 4.0.4 on 2022-05-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='The event description goes here'),
            preserve_default=False,
        ),
    ]
